### ISSUE TITLE
Samples of predictions and answers are not equal, {len(preds)}: {len(gts)}

### ISSUE THREAD

**Issue by tmarrakchi** [wasiahmad/PLBART#10]
Hi, 

I am trying to run the "run.sh" file, but I have the following error:

`fairseq-generate: error: argument --task: invalid choice: 'translation_from_pretrained_bart' (choose from 'translation', 'translation_lev', 'language_modeling', 'sentence_prediction', 'multilingual_translation', 'translation_moe', 'semisupervised_translation', 'sentence_ranking', 'multilingual_masked_lm', 'cross_lingual_lm', 'audio_pretraining', 'translation_from_pretrained_xlm', 'denoising', 'masked_lm', 'legacy_masked_lm')
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/PLBART-main/scripts/text_to_code/evaluator.py", line 46, in <module>
    main()
  File "/content/drive/MyDrive/Colab_Notebooks/PLBART-main/scripts/text_to_code/evaluator.py", line 29, in main
    assert len(preds) == len(gts), f"Samples of predictions and answers are not equal, {len(preds)}: {len(gts)}"
AssertionError: Samples of predictions and answers are not equal, 0: 2000
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/PLBART-main/evaluation/CodeBLEU/calc_code_bleu.py", line 34, in <module>
    assert len(hypothesis) == len(pre_references[i])
AssertionError`

Any idea please to fix this ?

**Comment by wasiahmad** [comment]
What version of Fairseq are you using?

**Comment by tmarrakchi** [comment]
fairseq==0.9.0

**Comment by wasiahmad** [comment]
I can see the error is due to the invalid task choice "translation_from_pretrained_bart" which is actually not part of fairseq==0.9.0. I see in v0.10.0, the task was introduced (https://github.com/pytorch/fairseq/tree/v0.10.0/fairseq/tasks). 

I am using `fairseq 0.9.0` but probably a later commit which consists of the `translation_from_pretrained_bart` task. Can you please try using `fairseq v0.10.0`?
