### ISSUE TITLE
Time required for fine-tuning

### ISSUE THREAD

**Issue by wangdeze18** [wasiahmad/PLBART#23]
Hi, thanks for your great work!
When I finetuned downstream tasks on my NVIDIA 3090, I roughly calculated that 100k fine-tuning steps would take 2 days. This does not seem very acceptable.  （Especially, CodeBERT takes only a few hours for fine-tuneing for the same task and dataset.）

Any suggestions?
Thanks！

**Comment by wasiahmad** [comment]
Not enough information was provided. Which tasks you are referring to? All the checkpoints are shared along with the log files, and you can check how much time it took for us to finetune the model. In my opinion, the runtime should be faster since we use Fairseq. The comparison with CodeBERT doesn't make sense to me.
